--[[
gen_conformance.lua - genera i vettori di conformita' della specifica s32
(docs/spec/s32-spec.md, sezione 9) usando i moduli di riferimento di lua32
(cpu.lua, ppu.lua, cart.lua, assembler.lua) - niente SDL, gira anche
headless:

    luajit tests/gen_conformance.lua

Scrive in docs/spec/conformance/ una cartuccia .cart e un file .vec per
ogni caso. Ogni riga del .vec e' un tick:

    <tick> <input> <crc WRAM> <crc VRAM..APU> <crc frame RGB> <A> <X> <Y> <FLAGS> <SP>

oppure "<tick> <input> crash". Un'altra implementazione (es. bm33) e'
conforme se riproduce tutte le righe. Le cartucce sono deterministiche
(uid a zero, data 0): rigenerare deve dare file identici.
]]
local script_dir = arg[0]:match("(.*/)") or "./"
package.path = script_dir .. "../?.lua;" .. package.path

local ffi = require("ffi")
local bit = require("bit")
local mm = require("memory_map")
local cpu_mod = require("cpu")
local ppu = require("ppu")
local cart = require("cart")
local asm = require("assembler")

local OUT = script_dir .. "../docs/spec/conformance/"
local W, H = 320, 224
local LOAD = 0x1000
local HW_BASE, HW_END = mm.VRAM_BASE, mm.APU_END

-- -----------------------------------------------------------
-- CRC32 su memoria FFI (stesso polinomio di cart.lua / zlib)
-- -----------------------------------------------------------
local crc_tab = ffi.new("uint32_t[256]")
for i = 0, 255 do
    local c = i
    for _ = 1, 8 do
        if bit.band(c, 1) ~= 0 then c = bit.bxor(0xEDB88320, bit.rshift(c, 1)) else c = bit.rshift(c, 1) end
    end
    crc_tab[i] = c
end
local function crc(ptr, n)
    local c = 0xFFFFFFFF
    for i = 0, n - 1 do
        c = bit.bxor(crc_tab[bit.band(bit.bxor(c, ptr[i]), 0xFF)], bit.rshift(c, 8))
    end
    return bit.tohex(bit.bnot(c))
end

-- -----------------------------------------------------------
-- helper: bytes, cartucce, esecuzione
-- -----------------------------------------------------------
local function bytes_to_string(t)
    local parts = {}
    for i = 1, #t do parts[i] = string.char(t[i]) end
    return table.concat(parts)
end

local function pack(name, src, stages, gfx, cgram)
    local code = bytes_to_string(asm.assemble(src, LOAD))
    cart.pack({
        meta = { uid = string.rep("\0", 16), title = "conformance: " .. name,
                 author = "s32 spec v0.1", created = 0 },
        code = code, stage_banks = stages or {}, gfx_banks = gfx or {}, cgram = cgram,
    }, OUT .. name .. ".cart")
    return OUT .. name .. ".cart"
end

local function run_vectors(name, cart_path, inputs)
    local loaded = cart.load(cart_path)
    local cpu = cpu_mod.new()
    cart.install(cpu, loaded, LOAD)
    local lines = {
        "# s32 conformance vectors, spec v0.1 - generated by tests/gen_conformance.lua",
        "# cart=" .. cart_path:match("[^/]+$") .. " ticks=" .. #inputs,
        "# tick input crc_wram crc_hw crc_frame A X Y FLAGS SP",
    }
    for t = 1, #inputs do
        local ib = inputs[t]
        local ok = pcall(cpu.run, cpu, LOAD, ib)
        if not ok then
            lines[#lines + 1] = string.format("%d %02x crash", t - 1, ib)
            break
        end
        local frame = ppu.render_frame(cpu.mem, cpu.scroll_x, cpu.scroll_y, W, H)
        lines[#lines + 1] = string.format("%d %02x %s %s %s %04x %04x %04x %02x %06x",
            t - 1, ib, crc(cpu.mem, mm.WRAM_END), crc(cpu.mem + HW_BASE, HW_END - HW_BASE),
            crc(frame, W * H * 3), cpu.a, cpu.x, cpu.y, cpu.flags, cpu.sp)
    end
    local f = assert(io.open(OUT .. name .. ".vec", "w"))
    f:write(table.concat(lines, "\n"), "\n")
    f:close()
    print(string.format("%-16s %4d tick -> %s.vec", name, #lines - 3, name))
end

-- sequenza di input deterministica: segmenti {byte, ripetizioni}
local function input_script(segments)
    local out = {}
    for _, s in ipairs(segments) do
        for _ = 1, s[2] do out[#out + 1] = s[1] end
    end
    return out
end

-- dispatcher: un blocco di test per tick, scelto da un contatore in WRAM
local COUNTER = 0x0100
local function dispatcher(blocks)
    local src = { "LDA " .. COUNTER, "INC " .. COUNTER }
    for i = 1, #blocks do
        src[#src + 1] = string.format("CMP #%d", i - 1)
        src[#src + 1] = string.format("JZ t%d", i - 1)
    end
    src[#src + 1] = "HALT"
    for i, b in ipairs(blocks) do
        src[#src + 1] = string.format("t%d:", i - 1)
        src[#src + 1] = b
        src[#src + 1] = "HALT"
    end
    return table.concat(src, "\n")
end

-- -----------------------------------------------------------
-- grafica di test (banchi, palette, stage)
-- -----------------------------------------------------------
local GFX_BANK_SIZE = mm.DIRECTORY_BYTES + mm.GRAPHICS_POOL_BYTES
local TILES = {  -- indice tile -> {offset nell'archivio, classe di taglia}
    [1] = {0, 0},     -- 8x8
    [5] = {64, 0},    -- 8x8 asimmetrico (freccia) per i flip
    [2] = {128, 1},   -- 16x16
    [3] = {384, 2},   -- 32x32
    [4] = {1408, 3},  -- 64x64
}

local function make_gfx_bank(variant)
    local b = ffi.new("uint8_t[?]", GFX_BANK_SIZE)
    for idx, t in pairs(TILES) do
        local d = idx * mm.DIRECTORY_ENTRY_BYTES
        b[d], b[d + 1], b[d + 2], b[d + 3] = t[1] % 256, math.floor(t[1] / 256) % 256, math.floor(t[1] / 65536), t[2]
    end
    local pool = mm.DIRECTORY_BYTES
    local function px(offset, size, x, y, v) b[pool + offset + y * size + x] = v end
    for y = 0, 7 do for x = 0, 7 do  -- tile 1: scacchiera con buchi trasparenti
        px(0, 8, x, y, ((x + y) % 3 == 0) and 0 or ((x * 3 + y + variant) % 7 + 1))
    end end
    for y = 0, 7 do for x = 0, 7 do  -- tile 5: freccia verso destra/in alto
        px(64, 8, x, y, (x >= y and y < 4) and (10 + x + variant) or 0)
    end end
    for y = 0, 15 do for x = 0, 15 do  -- tile 2: gradiente pieno
        px(128, 16, x, y, (x * 16 + y + variant * 3) % 255 + 1)
    end end
    for y = 0, 31 do for x = 0, 31 do  -- tile 3: cerchio, trasparente fuori
        local dx, dy = 2 * x - 31, 2 * y - 31
        px(384, 32, x, y, (dx * dx + dy * dy <= 31 * 31) and ((x + 2 * y + variant) % 200 + 20) or 0)
    end end
    for y = 0, 63 do for x = 0, 63 do  -- tile 4: strisce diagonali con buchi
        px(1408, 64, x, y, ((x + y) % 8 < 5) and ((x + y + variant * 5) % 100 + 100) or 0)
    end end
    return ffi.string(b, GFX_BANK_SIZE)
end

local function make_cgram()
    local c = ffi.new("uint8_t[?]", mm.CGRAM_SIZE)
    for p = 0, 7 do for i = 0, 255 do
        local a = (p * 256 + i) * 3
        c[a], c[a + 1], c[a + 2] = (i * 7 + p * 31) % 256, (i * 13 + p * 17) % 256, (i * 29 + p * 5) % 256
    end end
    return ffi.string(c, mm.CGRAM_SIZE)
end

local function make_stage(pattern)
    local s = ffi.new("uint8_t[?]", mm.TILEMAP_BYTES)
    for cy = 0, mm.TILEMAP_H - 1 do for cx = 0, mm.TILEMAP_W - 1 do
        local tile, pal = pattern(cx, cy)
        local w = ppu.encode_tile_descriptor(tile, pal)
        local a = (cy * mm.TILEMAP_W + cx) * 2
        s[a], s[a + 1] = w % 256, math.floor(w / 256)
    end end
    return ffi.string(s, mm.TILEMAP_BYTES)
end

-- stage 0: tutte le taglie mescolate, con sovrapposizioni e celle vuote
local stage0 = make_stage(function(cx, cy)
    local k = (cx * 7 + cy * 3) % 11
    local tile = ({0, 1, 1, 5, 2, 1, 3, 0, 1, 4, 2})[k + 1]
    return tile, (cx + 2 * cy) % 8
end)
-- stage 1: pochi tile grandi sparsi su fondo vuoto
local stage1 = make_stage(function(cx, cy)
    if cx % 9 == 0 and cy % 7 == 0 then return 4, (cx + cy) % 8 end
    if cx % 5 == 2 and cy % 4 == 1 then return 3, cy % 8 end
    if (cx + cy) % 13 == 0 then return 1, 3 end
    return 0, 0
end)

local gfx0, gfx1, cgram = make_gfx_bank(0), make_gfx_bank(1), make_cgram()

-- -----------------------------------------------------------
-- 1. demo.cart di lua32 (copiata cosi' com'e')
-- -----------------------------------------------------------
do
    local src = assert(io.open(script_dir .. "../cart/demo.cart", "rb"))
    local data = src:read("*a"); src:close()
    local dst = assert(io.open(OUT .. "demo.cart", "wb"))
    dst:write(data); dst:close()
    run_vectors("demo", OUT .. "demo.cart", input_script({
        {0x00, 5}, {0x01, 20}, {0x02, 30}, {0x04, 90}, {0x08, 40}, {0x10, 3},
        {0x05, 60}, {0x0A, 200}, {0x00, 2}, {0x09, 10}, {0x16, 10},
    }))
end

-- -----------------------------------------------------------
-- 2. CPU: un blocco di test per tick
-- -----------------------------------------------------------
do
    local R = 0x0200  -- area risultati in WRAM
    local blocks = {
        "LDA #0",                                                       -- Z
        "LDA #0x8000",                                                  -- N
        "LDA #0xFFFF\nADD #1",                                          -- C Z
        "LDA #0x7FFF\nADD #1",                                          -- V N
        "LDA #0x8000\nADD #0x8000",                                     -- C V Z
        "LDA #5\nSUB #7",                                               -- borrow
        "LDA #0x8000\nSUB #1",                                          -- V
        "LDA #7\nSUB #7",                                               -- Z C
        "LDA #0x0F0F\nAND #0x00FF\nSTA 0x0200\nOR #0xF000\nSTA 0x0202\nXOR #0xFFFF\nSTA 0x0204",
        "LDA #3\nCMP #3\nCMP #4",
        "LDA #9\nCMP #2\nCMP #0x8000",
        "LDA #0x8001\nASL\nSTA 0x0206\nLSR\nLSR",
        "LDA #0xFFFF\nSTA 0x0208\nINC 0x0208\nDEC 0x0208\nDEC 0x0208",
        "LDX #0\nDEX\nINY\nINY\nTXA\nTAY\nDEY\nTYX\nINX\nTXY",
        "LDA #0x1234\nPHA\nLDA #0\nPLA\nLDX #0x1111\nLDY #0x2222\nPHX\nPHY\nPLX\nPLY",
        "JSR sub1\nSTA 0x020A\nJMP after1\nsub1:\nLDA #0x4242\nJSR sub2\nRTS\nsub2:\nADD #1\nRTS\nafter1:",
        "LDX #4\nLDY #6\nLDA #0xAAAA\nSTA 0x0300,X\nLDA #0xBBBB\nSTA 0x0300,Y\nLDA 0x0300,X\nADD 0x0300,Y\nSTA 0x0310\nINC 0x0300,X\nDEC 0x0300,Y\nLDA #0xAAAB\nCMP 0x0300,X",
        "LDX #2\nLDY #4\nLDA #0x00F0\nSTA 0x0320\nLDA #0x0F00\nSTA 0x0322\nLDA #0xFFFF\nAND 0x031E,X\nOR 0x031E,Y\nXOR 0x0320,X\nSUB 0x031E,X\nSTA 0x0324\nSTX 0x0326,Y\nSTY 0x0326,X\nLDX 0x0326,Y\nLDY 0x0328,Y",
        "LDA #0xCDAB\nSTA 0xFFFFFF\nLDA #0\nLDA 0xFFFFFF\nSTA 0x0330\nLDX #2\nLDA 0xFFFFFF,X\nSTA 0x0332",
        "IN\nSTA 0x0340\nLDA 0x0AC800\nSTA 0x0342\nLDX 0x0AC7FF\nSTX 0x0344\nLDA #0\nOR 0x0AC800\nAND #0x10",
        "LDX #500\nCLAMPX 10,300\nLDY #5\nCLAMPY 10,300\nSTX 0x0350\nSTY 0x0352\nLDX #0xFFFF\nCLAMPX 0,0x8000",
        "LDA #1\nSTA 0x0AC801\nLDA 0x0AC801\nSTA 0x0360\nLDA #9\nSTA 0x0AC801",
        "LDA #13\nSTA 0x0AC802\nLDA #0x0107\nSTA 0x0AC803\nLDA 0x0AC802\nSTA 0x0362",
        "LDA #0\nSTA 0x0AC801\nLDA #1\nSTA 0x0AC805\nLDA #0x03FF\nSTA 0x0AC802",
        "LDA #0x00FF\nSTA 0x0AB003\nLDA #0x2040\nSTA 0x0AB005",           -- CGRAM via CPU
        "",                                                              -- flag persistenti
        "LDX #50000\nloop1:\nDEX\nJNZ loop1",                          -- ~100k istruzioni
        "LDA #0x5A5A\nSTA 0x0AC900\nSTA 0x0AC97E\nLDA #0x0101\nSTA 0x0AC808",
        "LDA #0\nSTA 0x0AC801\nLDA #0\nSTA 0x0AC805\nLDA #0\nSTA 0x0AC802\nSTA 0x0AC803",
    }
    local path = pack("cpu_ops", dispatcher(blocks), { [0] = stage0, [1] = stage1 },
                      { [0] = gfx0, [1] = gfx1 }, cgram)
    local inputs = {}
    for i = 1, #blocks + 3 do inputs[i] = (i * 37) % 32 end
    run_vectors("cpu_ops", path, inputs)
end

-- -----------------------------------------------------------
-- 3. PPU: scroll, stage, banchi grafici, sprite
-- -----------------------------------------------------------
do
    local OAM = mm.OAM_BASE
    local init = {}
    local function slot(n, x, y, tile, pal, attr)
        local base = OAM + n * 8
        init[#init + 1] = string.format("LDA #%d\nSTA %d", x % 65536, base)
        init[#init + 1] = string.format("LDA #%d\nSTA %d", y % 65536, base + 2)
        init[#init + 1] = string.format("LDA #%d\nSTA %d", ppu.encode_tile_descriptor(tile, pal), base + 4)
        init[#init + 1] = string.format("LDA #%d\nSTA %d", attr, base + 6)
    end
    slot(0, 20, 30, 2, 1, 1)
    slot(1, 28, 38, 3, 2, 1)            -- sopra lo slot 0
    slot(2, -8, 50, 4, 3, 1)            -- x negativa
    slot(3, 300, 200, 4, 4, 1)          -- esce a destra e in basso
    slot(4, 100, -20, 3, 5, 1 + 2)      -- flip x, y negativa
    slot(5, 140, 100, 5, 6, 1)          -- freccia normale
    slot(6, 150, 100, 5, 6, 1 + 2)      -- flip x
    slot(7, 160, 100, 5, 6, 1 + 4)      -- flip y
    slot(8, 170, 100, 5, 6, 1 + 2 + 4)  -- flip x+y
    slot(9, 200, 60, 0, 7, 1)           -- tile 0: disegnato (sprite)
    slot(10, 60, 60, 2, 0, 0)           -- invisibile
    slot(511, 24, 34, 1, 7, 1)          -- ultimo slot: sopra a tutti
    slot(12, -100, -100, 4, 0, 1)       -- completamente fuori schermo

    local SX, SY, INIT = 0x0400, 0x0402, 0x0404
    local src = table.concat({
        "LDA " .. INIT, "JNZ ready", table.concat(init, "\n"), "LDA #1", "STA " .. INIT,
        "ready:",
        -- scroll: +5 / +3 per tick
        "LDA " .. SX, "ADD #5", "STA " .. SX, "STA 0x0AC802",
        "LDA " .. SY, "ADD #3", "STA " .. SY, "STA 0x0AC803",
        -- sprite 0 si muove a destra
        "LDA " .. OAM, "ADD #2", "STA " .. OAM,
        -- eventi a tick fissi (contatore)
        "LDA " .. COUNTER, "INC " .. COUNTER,
        "CMP #20", "JNZ e1", "LDA #1", "STA 0x0AC801", "e1:",
        "LDA " .. (COUNTER), "CMP #31", "JNZ e2", "LDA #1", "STA 0x0AC805", "e2:",
        "LDA " .. COUNTER, "CMP #41", "JNZ e3", "LDA #0", "STA " .. (OAM + 6), "e3:",
        "LDA " .. COUNTER, "CMP #51", "JNZ e4", "LDA #0xFFF0", "STA " .. SX, "STA 0x0AC802", "e4:",
        "LDA " .. COUNTER, "CMP #56", "JNZ e5", "LDA #0", "STA 0x0AC801", "e5:",
        "HALT",
    }, "\n")
    local path = pack("ppu", src, { [0] = stage0, [1] = stage1 }, { [0] = gfx0, [1] = gfx1 }, cgram)
    local inputs = {}
    for i = 1, 64 do inputs[i] = 0 end
    run_vectors("ppu", path, inputs)
end

-- -----------------------------------------------------------
-- 4. crash: ogni caso termina con una riga "crash"
-- -----------------------------------------------------------
local function crash_case(name, body)
    -- due tick normali, poi il blocco che deve andare in crash
    local src = dispatcher({ "LDA #1", "LDA #2", body })
    local path = pack(name, src)
    run_vectors(name, path, { 0, 0, 0, 0 })
end
crash_case("crash_opcode", "LDA #0x00FF\nSTA 0x0400\nJMP 0x0400")        -- opcode 0xFF
crash_case("crash_underflow", "RTS")
-- il ciclo di push sta nella RAM libera (0x0B0000), non nella WRAM, cosi'
-- lo stack non lo sovrascrive: PHA; JMP 0x0B0000 = 70 60 00 00 0B
crash_case("crash_overflow",
    "LDA #0x6070\nSTA 0x0B0000\nLDA #0\nSTA 0x0B0002\nLDA #0x000B\nSTA 0x0B0004\nJMP 0x0B0000")
crash_case("crash_limit", "loop3:\nJMP loop3")

-- non e' un crash: lo stack scende fino a sovrascrivere il codice stesso
-- (a 0x1000), che diventa "RTS HALT" - deterministico, utile come test di
-- automodifica
do
    local path = pack("stack_smash", dispatcher({ "LDA #1", "LDA #2", "LDA #0x0168\nloop2:\nPHA\nJMP loop2" }))
    run_vectors("stack_smash", path, { 0, 0, 0, 0 })
end

print("vettori scritti in " .. OUT)
